[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.test-all]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test-no-default]
command = "cargo"
args = ["test", "--tests", "--lib", "--no-default-features"]

[tasks.miri]
install_crate = "miri"
command = "cargo"
args = ["+nightly", "miri", "test", "--tests", "--lib", "--no-default-features"]
dependencies = ["clean"]

[tasks.clean]
command = "cargo"
args = ["clean", "-p", "shipyard"]

[tasks.clippy]
env = { "RUSTFLAGS" = "-D warnings" }
command = "cargo"
args = ["clippy"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.doc]
env = { "RUSTFLAGS" = "-D warnings" }
command = "cargo"
args = ["doc", "--all-features", "--no-deps"]

[tasks.build_square_eater]
command = "cargo"
args = [
    "build",
    "--package",
    "square_eater",
    "--manifest-path",
    "square_eater/Cargo.toml",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.move_square_eater]
script_runner = "@shell"
script = '''
rm -f ./square_eater/public/square_eater.wasm
mv ./target/wasm32-unknown-unknown/release/square_eater.wasm ./square_eater/public/
'''

[tasks.square_eater]
run_task = { name = ["build_square_eater", "move_square_eater"] }

[tasks.test]
run_task = { name = ["format", "test-all", "doc", "miri", "clippy", "clean"] }

[tasks.cargo_visualizer]
command = "cargo"
args = [
    "build",
    "--package",
    "visualizer",
    "--manifest-path",
    "visualizer/Cargo.toml",
    "--lib",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.wasm_bindgen_visualizer]
install_crate = "wasm-bindgen-cli"
dependencies = ["cargo_visualizer"]
command = "wasm-bindgen"
args = [
    "target/wasm32-unknown-unknown/debug/visualizer.wasm",
    "--out-dir",
    "visualizer/out",
    "--no-modules",
    "--no-typescript",
]

[tasks.visualizer]
dependencies = ["wasm_bindgen_visualizer"]
install_crate = "miniserve"
command = "miniserve"
args = ["--spa", "--index", "index.html", "visualizer/out"]

[tasks.dev_visualizer]
install_crate = "watchexec-cli"
command = "watchexec"
args = ["-r", "-w", "visualizer/src", "cargo", "make", "visualizer"]
